noise: False  # specify if simulation should be run with or without noise
sampling_rate: 5.  # sampling rate in GHz used internally in the simulation.
speedup:
  minimum_weight_cut: 1.e-5
  delta_C_cut: 0.698  # 40 degree
  min_efield_amplitude: 2 #As a factor of noise RMS, Does not introduce bias as long as it is smaller than the trigger threshold
propagation:
  ice_model: mooresbay_simple
  attenuation_model: MB1
  attenuate_ice: True
  n_reflections: 1
  focusing: True
  focusing_limit: 2
signal:
  model: Alvarez2009
trigger:
  #Normally set to 300, to recreate Vrms for 100s/200s, use 690 for 100s, 850 for 200s
  noise_temperature: 300  # in Kelvin
#  noise_temperature: null #Null when setting Vrms
#  Vrms: 0.02  #20mV for 100s, 23mV for 200s
weights:
  weight_mode: core_mantle_crust # core_mantle_crust: use the three
  #layer earth model, which considers the different densities of the
  #core, mantle and crust. simple: use the simple earth model, which
  #apply a constant earth density

